services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:homolog
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-internal
      - services-bridge
    env_file:
      - .env
    expose:
      - 8080

  redis:
    container_name: evolution_redis
    image: redis:latest
    networks:
      - evolution-internal
    command: redis-server --port 6379 --appendonly yes
    volumes:
      - /data/evolution/redis:/data
    ports:
      - 6379:6379

  postgres:
    container_name: evolution_postgres
    image: postgres:15
    networks:
      - evolution-internal
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=evolution_postgres
      - POSTGRES_USER=evolution_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=evolution
      - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - /data/evolution/postgres:/var/lib/postgresql/data

volumes:
  evolution_instances:

networks:
  evolution-internal:
    driver: bridge
  services-bridge:
    external: true
    name: services-bridge
